# 规则名称: APTV
# 规则统计: 24

HOST,2a7ce3b9.wurl.com,policy
HOST,a1xs.vip,policy
HOST,aka-live1050.delivery.roku.com,policy
HOST,amg00276-amg00276c27-xumo-us-9597.playouts.now.amagi.tv,policy
HOST,czstream.com,policy
HOST,d198ro05q94rc4.cloudfront.net,policy
HOST,dbrb49pjoymg4.cloudfront.net,policy
HOST,dmr1h4skdal9h.cloudfront.net,policy
HOST,e.erw.cc,policy
HOST,epg.aptv.app,policy
HOST,fast-tv-proxy.sharewithyou.dpdns.org,policy
HOST,lb59.xxip9.top,policy
HOST,provider-static.plex.tv,policy
HOST,share.sharewithyou.dpdns.org,policy
HOST,siloh-ns1.plutotv.net,policy
HOST,sk.delivery.roku.com,policy
HOST,tg-sub-bot.sharewithyou.dpdns.org,policy
HOST,tst-01.worldcast.tv,policy
HOST,tvpnlogopeu.samsungcloud.tv,policy
HOST,wurlfifa.global.transmit.live,policy
HOST-SUFFIX,edemist.com,policy
HOST-SUFFIX,fomo.re,policy
HOST-SUFFIX,funke.video,policy
HOST-SUFFIX,moveonjoy.com,policy
