# 规则名称: GitHub
# 规则统计: 62

HOST,copilot-proxy.githubusercontent.com,policy
HOST,copilot-workspace.githubnext.com,policy
HOST,copilotprodattachments.blob.core.windows.net,policy
HOST,github-api.arkoselabs.com,policy
HOST,github-cloud.s3.amazonaws.com,policy
HOST,github-production-release-asset-2e65be.s3.amazonaws.com,policy
HOST,github-production-repository-file-5c1aeb.s3.amazonaws.com,policy
HOST,github-production-repository-image-32fea6.s3.amazonaws.com,policy
HOST,github-production-upload-manifest-file-7fdce7.s3.amazonaws.com,policy
HOST,github-production-user-asset-6210df.s3.amazonaws.com,policy
HOST,mavenregistryv2prod.blob.core.windows.net,policy
HOST,npmregistryv2prod.blob.core.windows.net,policy
HOST,nugetregistryv2prod.blob.core.windows.net,policy
HOST,productionresultssa0.blob.core.windows.net,policy
HOST,productionresultssa1.blob.core.windows.net,policy
HOST,productionresultssa10.blob.core.windows.net,policy
HOST,productionresultssa11.blob.core.windows.net,policy
HOST,productionresultssa12.blob.core.windows.net,policy
HOST,productionresultssa13.blob.core.windows.net,policy
HOST,productionresultssa14.blob.core.windows.net,policy
HOST,productionresultssa15.blob.core.windows.net,policy
HOST,productionresultssa16.blob.core.windows.net,policy
HOST,productionresultssa17.blob.core.windows.net,policy
HOST,productionresultssa18.blob.core.windows.net,policy
HOST,productionresultssa19.blob.core.windows.net,policy
HOST,productionresultssa2.blob.core.windows.net,policy
HOST,productionresultssa3.blob.core.windows.net,policy
HOST,productionresultssa4.blob.core.windows.net,policy
HOST,productionresultssa5.blob.core.windows.net,policy
HOST,productionresultssa6.blob.core.windows.net,policy
HOST,productionresultssa7.blob.core.windows.net,policy
HOST,productionresultssa8.blob.core.windows.net,policy
HOST,productionresultssa9.blob.core.windows.net,policy
HOST,rubygemsregistryv2prod.blob.core.windows.net,policy
HOST-SUFFIX,atom.io,policy
HOST-SUFFIX,dependabot.com,policy
HOST-SUFFIX,gh.io,policy
HOST-SUFFIX,ghcr.io,policy
HOST-SUFFIX,ghe.com,policy
HOST-SUFFIX,git.io,policy
HOST-SUFFIX,github.ai,policy
HOST-SUFFIX,github.blog,policy
HOST-SUFFIX,github.career,policy
HOST-SUFFIX,github.com,policy
HOST-SUFFIX,github.community,policy
HOST-SUFFIX,github.dev,policy
HOST-SUFFIX,github.io,policy
HOST-SUFFIX,githubapp.com,policy
HOST-SUFFIX,githubassets.com,policy
HOST-SUFFIX,githubcopilot.com,policy
HOST-SUFFIX,githubhackathon.com,policy
HOST-SUFFIX,githubnext.com,policy
HOST-SUFFIX,githubpreview.dev,policy
HOST-SUFFIX,githubstatus.com,policy
HOST-SUFFIX,githubsupport.com,policy
HOST-SUFFIX,githubuniverse.com,policy
HOST-SUFFIX,githubusercontent.com,policy
HOST-SUFFIX,myoctocat.com,policy
HOST-SUFFIX,octocaptcha.com,policy
HOST-SUFFIX,opensource.guide,policy
HOST-SUFFIX,repo.new,policy
HOST-SUFFIX,thegithubshop.com,policy
