# 规则名称: Google
# 规则统计: 23

HOST-SUFFIX,1e100.net,policy
HOST-SUFFIX,2mdn.net,policy
HOST-SUFFIX,app-measurement.net,policy
HOST-SUFFIX,c.gle,policy
HOST-SUFFIX,g.co,policy
HOST-SUFFIX,ggpht.com,policy
HOST-SUFFIX,goo.gl,policy
HOST-SUFFIX,googleapis.cn,policy
HOST-SUFFIX,googleapis.com,policy
HOST-SUFFIX,gstatic.cn,policy
HOST-SUFFIX,gstatic.com,policy
HOST-SUFFIX,gvt0.com,policy
HOST-SUFFIX,gvt1.com,policy
HOST-SUFFIX,gvt2.com,policy
HOST-SUFFIX,gvt3.com,policy
HOST-SUFFIX,xn--ngstr-lra8j.com,policy
HOST-SUFFIX,youtu.be,policy
HOST-SUFFIX,youtube-nocookie.com,policy
HOST-SUFFIX,youtube.com,policy
HOST-SUFFIX,yt.be,policy
HOST-SUFFIX,ytimg.com,policy
HOST-KEYWORD,gmail,policy
HOST-KEYWORD,google,policy
