# 规则名称: LINE
# 规则统计: 20

HOST-SUFFIX,gcld-line.com,policy
HOST-SUFFIX,lin.ee,policy
HOST-SUFFIX,line-apps-beta.com,policy
HOST-SUFFIX,line-apps-rc.com,policy
HOST-SUFFIX,line-apps.com,policy
HOST-SUFFIX,line-beta.me,policy
HOST-SUFFIX,line-cdn.net,policy
HOST-SUFFIX,line-scdn.net,policy
HOST-SUFFIX,line.biz,policy
HOST-SUFFIX,line.me,policy
HOST-SUFFIX,line.naver.jp,policy
HOST-SUFFIX,linecorp.com,policy
HOST-SUFFIX,linefriends.com,policy
HOST-SUFFIX,linefriends.com.tw,policy
HOST-SUFFIX,linegame.jp,policy
HOST-SUFFIX,linemobile.com,policy
HOST-SUFFIX,linemyshop.com,policy
HOST-SUFFIX,lineshoppingseller.com,policy
HOST-SUFFIX,linetv.tw,policy
HOST-SUFFIX,nhncorp.jp,policy
