# 规则名称: Netflix
# 规则统计: 32

HOST-SUFFIX,fast.com,policy
HOST-SUFFIX,flxvpn.net,policy
HOST-SUFFIX,netflix.ca,policy
HOST-SUFFIX,netflix.com,policy
HOST-SUFFIX,netflix.com.au,policy
HOST-SUFFIX,netflix.com.edgesuite.net,policy
HOST-SUFFIX,netflix.net,policy
HOST-SUFFIX,netflixdnstest0.com,policy
HOST-SUFFIX,netflixdnstest1.com,policy
HOST-SUFFIX,netflixdnstest10.com,policy
HOST-SUFFIX,netflixdnstest2.com,policy
HOST-SUFFIX,netflixdnstest3.com,policy
HOST-SUFFIX,netflixdnstest4.com,policy
HOST-SUFFIX,netflixdnstest5.com,policy
HOST-SUFFIX,netflixdnstest6.com,policy
HOST-SUFFIX,netflixdnstest7.com,policy
HOST-SUFFIX,netflixdnstest8.com,policy
HOST-SUFFIX,netflixdnstest9.com,policy
HOST-SUFFIX,netflixinvestor.com,policy
HOST-SUFFIX,netflixstudios.com,policy
HOST-SUFFIX,netflixtechblog.com,policy
HOST-SUFFIX,nflxext.com,policy
HOST-SUFFIX,nflximg.com,policy
HOST-SUFFIX,nflximg.net,policy
HOST-SUFFIX,nflxsearch.net,policy
HOST-SUFFIX,nflxso.net,policy
HOST-SUFFIX,nflxvideo.net,policy
HOST-KEYWORD,apiproxy-device-prod-nlb-,policy
HOST-KEYWORD,dualstack.apiproxy-,policy
HOST-KEYWORD,dualstack.ichnaea-web-,policy
HOST-KEYWORD,netflixdnstest,policy
USER-AGENT,Argo*,policy
