# 规则名称: OKX
# 规则统计: 9

HOST-SUFFIX,okex.com,policy
HOST-SUFFIX,okx-dns.com,policy
HOST-SUFFIX,okx-dns1.com,policy
HOST-SUFFIX,okx-dns2.com,policy
HOST-SUFFIX,okx.ac,policy
HOST-SUFFIX,okx.cab,policy
HOST-SUFFIX,okx.com,policy
HOST-SUFFIX,okx.com.cdn.cloudflare.net,policy
HOST-SUFFIX,xlayer.tech,policy
