# 规则名称: ParamountPlus
# 规则统计: 10

HOST,cbsi.live.ott.irdeto.com,policy
HOST,cbsplaylistserver.aws.syncbak.com,policy
HOST,cbsservice.aws.syncbak.com,policy
HOST,link.theplatform.com,policy
HOST-SUFFIX,cbsaavideo.com,policy
HOST-SUFFIX,cbsi.com,policy
HOST-SUFFIX,cbsivideo.com,policy
HOST-SUFFIX,paramountplus.com,policy
HOST-SUFFIX,pplusstatic.com,policy
USER-AGENT,PPlus*,policy
