# 规则名称: PrimeVideo
# 规则统计: 16

HOST,atv-ps.amazon.com,policy
HOST,avodmp4s3ww-a.akamaihd.net,policy
HOST,d1v5ir2lpwr8os.cloudfront.net,policy
HOST,d22qjgkvxw22r6.cloudfront.net,policy
HOST,d25xi40x97liuc.cloudfront.net,policy
HOST,d27xxe7juh1us6.cloudfront.net,policy
HOST,dmqdd6hw24ucf.cloudfront.net,policy
HOST,fls-na.amazon.com,policy
HOST,www.amazon.com,policy
HOST-SUFFIX,aiv-cdn.net,policy
HOST-SUFFIX,aiv-delivery.net,policy
HOST-SUFFIX,amazonvideo.com,policy
HOST-SUFFIX,media-amazon.com,policy
HOST-SUFFIX,primevideo.com,policy
HOST-SUFFIX,pv-cdn.net,policy
HOST-KEYWORD,avoddashs,policy
