# 规则名称: Telegram
# 规则统计: 15

HOST,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe,policy
HOST-SUFFIX,cdn-telegram.org,policy
HOST-SUFFIX,graph.org,policy
HOST-SUFFIX,legra.ph,policy
HOST-SUFFIX,t.me,policy
HOST-SUFFIX,tdesktop.com,policy
HOST-SUFFIX,telega.one,policy
HOST-SUFFIX,telegra.ph,policy
HOST-SUFFIX,telegram.dog,policy
HOST-SUFFIX,telegram.me,policy
HOST-SUFFIX,telegram.org,policy
HOST-SUFFIX,telegram.space,policy
HOST-SUFFIX,telesco.pe,policy
HOST-SUFFIX,tg.dev,policy
HOST-SUFFIX,tx.me,policy
