# 规则名称: TikTok
# 规则统计: 80

HOST,api.snapkit.com,policy
HOST,cocacola.co.jp,policy
HOST,courses.snapsolve.com,policy
HOST,engagements.appsflyer.com,policy
HOST,lf16-campaign.ttlstatic.com,policy
HOST,lf16-csp.oecstatic.com,policy
HOST,lf16-pkgcdn.pitaya-clientai.com,policy
HOST,lf16-scmcdn.oecstatic.com,policy
HOST,lf19-csp.oecstatic.com,policy
HOST,lf19-pkgcdn.pitaya-clientai.com,policy
HOST,lf19-scmcdn.oecstatic.com,policy
HOST,musically-alternate.app.link,policy
HOST,musically.app.link,policy
HOST,p1-tt-ipv6.byteimg.com,policy
HOST,p1-tt.byteimg.com,policy
HOST,p26-tt.byteimg.com,policy
HOST,p3-tt-ipv6.byteimg.com,policy
HOST,p9-tt.byteimg.com,policy
HOST,roovza-launches.appsflyersdk.com,policy
HOST-SUFFIX,bytedance.net,policy
HOST-SUFFIX,bytedapm.com,policy
HOST-SUFFIX,bytefcdn-oversea.com,policy
HOST-SUFFIX,bytefcdn-ttpeu.com,policy
HOST-SUFFIX,bytegecko-i18n.com,policy
HOST-SUFFIX,byteglb.com,policy
HOST-SUFFIX,byteicdn.com,policy
HOST-SUFFIX,byteigtm.com,policy
HOST-SUFFIX,byteintl.com,policy
HOST-SUFFIX,byteintl.net,policy
HOST-SUFFIX,byteoversea.com,policy
HOST-SUFFIX,byteoversea.net,policy
HOST-SUFFIX,bytetcdn.com,policy
HOST-SUFFIX,capcut.com,policy
HOST-SUFFIX,ibytedtos.com,policy
HOST-SUFFIX,ibyteimg.com,policy
HOST-SUFFIX,ipstatp.com,policy
HOST-SUFFIX,isnssdk.com,policy
HOST-SUFFIX,muscdn.com,policy
HOST-SUFFIX,musemuse.cn,policy
HOST-SUFFIX,musical.ly,policy
HOST-SUFFIX,pstatp.com,policy
HOST-SUFFIX,sgpstatp.com,policy
HOST-SUFFIX,sgsnssdk.com,policy
HOST-SUFFIX,tik-tokapi.com,policy
HOST-SUFFIX,tiktok-usts.net,policy
HOST-SUFFIX,tiktok.com,policy
HOST-SUFFIX,tiktok.in,policy
HOST-SUFFIX,tiktokcdn-eu.com,policy
HOST-SUFFIX,tiktokcdn-eu.net,policy
HOST-SUFFIX,tiktokcdn-in.com,policy
HOST-SUFFIX,tiktokcdn-us.com,policy
HOST-SUFFIX,tiktokcdn.com,policy
HOST-SUFFIX,tiktokd.net,policy
HOST-SUFFIX,tiktokd.org,policy
HOST-SUFFIX,tiktokglobalshop.com,policy
HOST-SUFFIX,tiktokglobalshopv.com,policy
HOST-SUFFIX,tiktokmusic.app,policy
HOST-SUFFIX,tiktokshop.com,policy
HOST-SUFFIX,tiktokstaticb.com,policy
HOST-SUFFIX,tiktokv.com,policy
HOST-SUFFIX,tiktokv.eu,policy
HOST-SUFFIX,tiktokv.us,policy
HOST-SUFFIX,tiktokw.us,policy
HOST-SUFFIX,tlivecdn.com,policy
HOST-SUFFIX,tlivepush.com,policy
HOST-SUFFIX,ttadsmanager.com,policy
HOST-SUFFIX,ttapis.com,policy
HOST-SUFFIX,ttdns2.com,policy
HOST-SUFFIX,ttlivecdn.com,policy
HOST-SUFFIX,ttoversea.net,policy
HOST-SUFFIX,ttoverseaus.net,policy
HOST-SUFFIX,ttwstatic.com,policy
HOST-SUFFIX,tzvbfs.com,policy
HOST-KEYWORD,bytedance.map.,policy
HOST-KEYWORD,musical.ly.,policy
HOST-KEYWORD,tiktokcdn-,policy
HOST-KEYWORD,tiktokcdn.com.,policy
HOST-KEYWORD,tiktokv.com.,policy
HOST-KEYWORD,ttcdn-tos.,policy
HOST-KEYWORD,ttlivecdn.com.,policy
