# 规则名称: Twitch
# 规则统计: 9

HOST-SUFFIX,ext-twitch.tv,policy
HOST-SUFFIX,jtvnw.net,policy
HOST-SUFFIX,live-video.net,policy
HOST-SUFFIX,ttvnw.net,policy
HOST-SUFFIX,twitch-ext.rootonline.de,policy
HOST-SUFFIX,twitch.tv,policy
HOST-SUFFIX,twitchcdn.net,policy
HOST-SUFFIX,twitchsvc.net,policy
HOST-KEYWORD,ttvnw,policy
