# 规则名称: WhatsApp
# 规则统计: 11

HOST-SUFFIX,wa.me,policy
HOST-SUFFIX,whatsapp-plus.info,policy
HOST-SUFFIX,whatsapp-plus.me,policy
HOST-SUFFIX,whatsapp-plus.net,policy
HOST-SUFFIX,whatsapp.cc,policy
HOST-SUFFIX,whatsapp.com,policy
HOST-SUFFIX,whatsapp.info,policy
HOST-SUFFIX,whatsapp.net,policy
HOST-SUFFIX,whatsapp.org,policy
HOST-SUFFIX,whatsapp.tv,policy
HOST-SUFFIX,whatsappbrand.com,policy
