# 规则名称: X
# 规则统计: 26

HOST-SUFFIX,ads-twitter.com,policy
HOST-SUFFIX,cms-twdigitalassets.com,policy
HOST-SUFFIX,grok.com,policy
HOST-SUFFIX,periscope.tv,policy
HOST-SUFFIX,pscp.tv,policy
HOST-SUFFIX,t.co,policy
HOST-SUFFIX,tellapart.com,policy
HOST-SUFFIX,tweetdeck.com,policy
HOST-SUFFIX,twimg.co,policy
HOST-SUFFIX,twimg.com,policy
HOST-SUFFIX,twimg.org,policy
HOST-SUFFIX,twitpic.com,policy
HOST-SUFFIX,twitter.biz,policy
HOST-SUFFIX,twitter.com,policy
HOST-SUFFIX,twitter.jp,policy
HOST-SUFFIX,twittercommunity.com,policy
HOST-SUFFIX,twitterflightschool.com,policy
HOST-SUFFIX,twitterinc.com,policy
HOST-SUFFIX,twitteroauth.com,policy
HOST-SUFFIX,twitterstat.us,policy
HOST-SUFFIX,twtrdns.net,policy
HOST-SUFFIX,twttr.com,policy
HOST-SUFFIX,twttr.net,policy
HOST-SUFFIX,twvid.com,policy
HOST-SUFFIX,vine.co,policy
HOST-SUFFIX,x.com,policy
