# 规则名称: APTV
# 规则统计: 24

DOMAIN,2a7ce3b9.wurl.com
DOMAIN,a1xs.vip
DOMAIN,aka-live1050.delivery.roku.com
DOMAIN,amg00276-amg00276c27-xumo-us-9597.playouts.now.amagi.tv
DOMAIN,czstream.com
DOMAIN,d198ro05q94rc4.cloudfront.net
DOMAIN,dbrb49pjoymg4.cloudfront.net
DOMAIN,dmr1h4skdal9h.cloudfront.net
DOMAIN,e.erw.cc
DOMAIN,epg.aptv.app
DOMAIN,fast-tv-proxy.sharewithyou.dpdns.org
DOMAIN,lb59.xxip9.top
DOMAIN,provider-static.plex.tv
DOMAIN,share.sharewithyou.dpdns.org
DOMAIN,siloh-ns1.plutotv.net
DOMAIN,sk.delivery.roku.com
DOMAIN,tg-sub-bot.sharewithyou.dpdns.org
DOMAIN,tst-01.worldcast.tv
DOMAIN,tvpnlogopeu.samsungcloud.tv
DOMAIN,wurlfifa.global.transmit.live
DOMAIN-SUFFIX,edemist.com
DOMAIN-SUFFIX,fomo.re
DOMAIN-SUFFIX,funke.video
DOMAIN-SUFFIX,moveonjoy.com
